### ISSUE TITLE
FormatException: String was not recognized as a valid DateTime in GK_SavedGame constructor

### ISSUE THREAD

**Issue by AlexYaremenko** [StansAssets/Development#110]
Hi,
I have my application localized in multiple languages, and I switch the current Culture to the corresponding one, so that number formatting and special letters (see Turkish) are handled correctly.
I suspect that this could be the reason why I'm getting this exception from some users:

FormatException: String was not recognized as a valid DateTime.
System.DateTime.CoreParse (System.String s, IFormatProvider provider, DateTimeStyles styles, DateTime& result, DateTimeOffset& dto, Boolean setExceptionOnError, System.Exception& exception)
GK_SavedGame..ctor (System.String id, System.String name, System.String device, System.String dateString)
ISN_GameSaves.DeserializeGameSave (System.String serializedData)
ISN_GameSaves.OnSaveSuccess (System.String data)

I don't know if, maybe, specifying the CultureInfo.InvariantCulture to your Parse call could resolve the issue.
Do you confirm that this could be a possible fix?

Edit:
Also, another possible option to consider. 
Quoting this documentation https://developer.apple.com/reference/foundation/nsdateformatter?language=objc 
- For most fixed formats, you should also set the locale property to a POSIX locale ("en_US_POSIX"), and set the timeZone property to UTC.
But in your source code, there is no locale and timezone set.__

**Comment by lacosto** [comment]
done
