### ISSUE TITLE
Update code compatibility fro for Unity 5.6 (All plugins)

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#114]

**Comment by frosting17** [comment]
Android Native scenes:

BillingExample -> ✔
BillingImplementationExample -> ✔
GoogleAdExample -> ✔
SocialSharing -> ✔
TwitterExample -> ✔
PlayServiceExample -> ✔
Custom Leaderboard UI -> ✔
Quests & Events -> ✔
Notifications ->
Native Pop-ups -> ✔
Native API -> **☓**
Get App License Status - result is empty.

Google Cloud -> **☓** Удалить
Google+ btn -> **☓**
btn invisible. Bug comes from Google + Unity_5.6
Preview -> **☓**
remove button **I found a bug**.
remove button **Google Cloud** Удалить.

**Comment by frosting17** [comment]
iOS Native scenes:

Preview -> 
Удалить кнопки:
iAd App Network
iAd No Coding Example

CloudKitExampleScene -> ✔
GameSavesExample -> ✔
iCloudExampleScene ->  ✔
MediaExample ->  ✔
**NativeIOSActionsExample** ->✔
Check if FB app exists -> не работает(хотя апп установлено)

NotificationExample ->  ✔
PopUpsAndAppEventHandler -> ✔
ReplayKitExampleScene -> Failed To Start = -5803(включен API в настройкаx)
SocialPostingExample -> ✔
WhatsApp -
Share text - -canOpenURL: failed for URL: "whatsapp://send?text=Some%20text" - error: "(null)"
Share Image - не работает. Нет вызова никакого.

BillingExample -> ✔
CustomLeaderboardGUIExample -> ✔

**FriendsLoadExample** ->✔
Challenge Achievement - вызывает краш.

**GameCenterGeneral** ->✔
ShowLeaderboard1 - не открывает leaderboard(открывает вкладку leaderboards)
ShowLeaderboard2 - не открывает leaderboard(открывает вкладку leaderboards)
SendLeaderboardChallenge - вызывает краш приложения.

Peer-to-PeerGameExample -> ✔ слетел скрипт GameManager
RTM_MultiplayerExample -> ✔ не работает функционал
TBD_MultiplayerExample -> ✔ крашит скрипт TBM_Multiplayer_Example.cs:36

**Comment by frosting17** [comment]
Mobile Native PopUps scene:
MobilePopUpsExample -> ✔

**Comment by frosting17** [comment]
SocialGif scene:
Demo ->  ✔

**Comment by frosting17** [comment]
Google Mobile Ads SDK scenes:
Example ->  ✔
NoCodingExample -> ✔

**Comment by frosting17** [comment]
Mobile Social Plugin scenes:
FacebookExample ->  ✔
TwitterExample ->  ✔
MSP_Preview ->  ✔
MoreExamples ->  ✔

**Comment by frosting17** [comment]
Ultimate Mobile scenes:

UM_Social -> 
не работает постинг в Twitter & Facebook при использовании mono2x scripting backend.

Не добавляется пост процессом UserNotifications.framework

UM_BillingPreview - message & code -> code & message

**Comment by frosting17** [comment]
Native API -> ✔
Get App License Status - result is empty.
**Исправлено отображение статуса лицензии**

Google+ btn -> ✔
btn invisible. Bug comes from Google + Unity_5.6
**Будет пофикшено с новой версией Google AdMob libs**

Preview -> ✔
button I found a bug
button Google Cloud Удалить
**В новой версии будет удалены**

NativeIOSActionsExample -> ✔
Check if FB app exists -> не работает(хотя апп установлено)
**Нужно добавить fb в LSApplicationQueriesSchemes**

ReplayKitExampleScene ->  ✔
Failed To Start = -5803(включен API в настройкаx)
**Работает на новом iPad. Или на любом девайсе 10.1**

SocialPostingExample -> ✔
WhatsApp -
Share text - -canOpenURL: failed for URL: "whatsapp://send?text=Some%20text" - error: "(null)"
Share Image - не работает. Нет вызова никакого.
**Проблема была в незнании, что WhatsApp на iPad 2 mini не работает**

BillingExample -> ✔
CustomLeaderboardGUIExample -> ✔

UM_BillingPreview -> ✔
message & code -> code & message
**Пофикшено**

Не добавляется пост процессом UserNotifications.framework - ✔
**Пофикшено**

FriendsLoadExample -> ✔
**GameCenter больше не поддерживает этот функционал**

GameCenterGeneral -> ✔
ShowLeaderboard1 - не открывает leaderboard(открывает вкладку leaderboards)
ShowLeaderboard2 - не открывает leaderboard(открывает вкладку leaderboards)
**Apple баг, которому уже 2 года**

SendLeaderboardChallenge - вызывает краш приложения - ☓

Peer-to-PeerGameExample -> ☓ слетел скрипт GameManager
RTM_MultiplayerExample -> ☓ не работает функционал
TBD_MultiplayerExample -> ☓ крашит скрипт TBM_Multiplayer_Example.cs:36

**Comment by frosting17** [comment]
Peer-To-PeerGameExample слетевший скрипт + нет дока. Хрен его как он вообще работает.
RTM_MultiplayerExample -> ☓ висит таск на интеграцию
TMB_Multiplayer_Example -> X крашит в Editor'e.
