### ISSUE TITLE
SG update

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#115]
The plug-in works fine, but needs to update the Twitter upload process to this approach - https://xcodenoobies.blogspot.bg/2016/01/how-to-using-slrequest-to-upload-image.html

Also the Facebook gif upload uses the free API key for Giphy, which may work at some point, but it may stop working. The author needs to add the Giphy "powered by" banner and give an option to setup a personal Giphy key.

**Comment by AlexYaremenko** [comment]
Android ready

**Comment by frosting17** [comment]
iOS ready
