### ISSUE TITLE
Баги iOS Native

### ISSUE THREAD

**Issue by frosting17** [StansAssets/Development#131]
Настройки плагина дефолтные. При билде плюется на это(видимо календарь АПИ):
![2](https://cloud.githubusercontent.com/assets/11818381/26552563/57fd329c-4490-11e7-95b9-53cad17599cd.png)

Также Рома реализовал календарь, через класс, который уже депрекейт в 8.0. Раз это новое АПИ, надо использовать последние изменения:
![1](https://cloud.githubusercontent.com/assets/11818381/26552545/48682260-4490-11e7-80c8-f736ae6d5e39.png)

**Comment by lacosto** [comment]
fixed
