### ISSUE TITLE
Google+ button is not visible

### ISSUE THREAD

**Issue by KrasovskyVictor** [StansAssets/Development#136]
1- The Google+ button with plus count is not visible on the device screen. I can click in the area where it's supposed to be and it does indeed show the Google+ UI but the button itself is not visible.

Протестировал на тестовой сцене, Unity 5.6.1f1 - да, действительно кнопка google + не видна, но кликабельна.

**Comment by KrasovskyVictor** [comment]
upd: Unity 5.5.1f1 - всё работает отлично.
Скорее всего, проблема появилась после обновления  5.6

**Comment by AlexYaremenko** [comment]
Fixed in Unity 5.6.2f1
