### ISSUE TITLE
В последней версии UM возникла проблема с локальными нотификациями на андроид

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#16]
В последней версии UM возникла проблема с локальными нотификациями на андроид
https://unionassets.com/android-native-plugin/local-notifications-90
здесь написано, что можно ставить разные звуки для пуша, положив нужный wav файл в Plugins/Android/AN_Res/res/raw и прописав во время создания пуша builder.SetSoundName("local_push.wav");
В итоге звук меняется на стандартный, хотя в сбилженном APK этот wav файл есть.

P.S.  перекинь плз на меня как зафиксиш

**Comment by AlexYaremenko** [comment]
Виктор, протестируй, пожалуйста, и если рили такая тема репродьюсится, то нужно фиксить.
Спасибо!

**Comment by KrasovskyVictor** [comment]
@AlexYaremenko да, действительно репродюсится. При установке Sound Name из когда - всегда воспроизводится стандартный звук.
