### ISSUE TITLE
Add sign out support

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#170]
Раньше мы использовали вот этот плагин (https://github.com/playgameservices/play-games-plugin-for-unity)
У них есть методы
PlayGamesPlatform.Instance.Authenticate(Action<bool> callback, bool silent);
Аргумент silent, помогал авторизовать пользователя в фоновом режиме, если он уже ранее был авторизован.
Если аргумент silent не установлен, то пользователю выдается окно, запрашивающее авторизацию.
PlayGamesPlatform.Instance.SignOut();
SignOut позволял выйти пользователю из аккаунта, в последствии авторизация в режиме silent уже не работала и простая авторизация выдавала игроку окно с запросом авторизации.

С вашей библиотекой все работает иначе. У вас почему-то два метода, Disconnect и ClearDefaultAccount.
Хотелось бы решить этот вопрос, потому как игрок сейчас не может выйти из своего аккаунта, это не работает на большинстве устройств.

**Comment by AlexYaremenko** [comment]
Done!
