### ISSUE TITLE
iOS Native build for (UWP)Windows

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#171]
The asset is fine and all. But I also build for windows and don't want to remove your plugin each time I do that. When I build for windows 10 universal I get the folowing errors:

Reference rewriter: Error: type `System.Security.Cryptography.HMACSHA256` doesn't exist in target framework. It is referenced from Assembly-CSharp-firstpass.dll at System.String SA.Common.Util.General::HMAC(System.String,System.String).

But a lot of them, I dont get it, since it should not be included in the build at all. Can this be fixed?

**Comment by lacosto** [comment]
fixed
