### ISSUE TITLE
AdMob (iOS platform) Smart banner doesn't stretched

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#172]
I used Very Simple ads pack from assetstore before buying your package. If you want i can provide that package.

Admob Banner works perfectly fine on ipad as well.

I only see the issue in ultimate mobile pack.

Please have a look at the attached image and link.

https://developers.google.com/admob/ios/banner

**Comment by lacosto** [comment]
what kind of issue?

**Comment by lacosto** [comment]
в коде у нас все правильно, проверил несколько рас.
Добавь в know issues:
https://stackoverflow.com/a/34192619

**Comment by DonaldQuack** [comment]
Done.

https://unionassets.com/google-mobile-ads-sdk/smart-banner-doesn-t-stretched-ios-platform-598
