### ISSUE TITLE
Have to change hierarchy of the MNP

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#178]
Doesn't have same hierarchy like other plugins. Screenshots attached.
Unity doesn't import few plugins properly.

MNP_Files.cs doesn't have namespace. It causes conflicts between two or more or plugins.

![isn settings](https://user-images.githubusercontent.com/11818381/29870491-610d7ec0-8d90-11e7-827d-20c3ccbe5b2f.png)
![mnp settings](https://user-images.githubusercontent.com/11818381/29870492-610f8512-8d90-11e7-9f3c-900550521ffb.png)

**Comment by AlexYaremenko** [comment]
Fixed!!!
