### ISSUE TITLE
Compilation error in new clean project

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#179]
Build system - Internal default
Unity 5.6.2 or higher

Log:
/Temp/StagingArea/AndroidManifest-main.xml:6:16-49 Error:
Attribute application@icon value=(@drawable/app_icon) from AndroidManifest-main.xml:6:16-49
	is also present at AndroidManifest.xml:13:9-45 value=(@drawable/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest-main.xml:6:3-47:17 to override.

Temporary fix:
1) Open main AndroidManifest.xml by path: Plugins -> Android:
2) Add this field xmlns:tools="http://schemas.android.com/tools" to tag <Manifest 
3) Then add this param tools:replace="android:icon" to tag <Application

**Comment by AlexYaremenko** [comment]
Fixed!
