### ISSUE TITLE
the playmaker isn_purchase action 

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#184]
i have a problem with iOS native. the playmaker isn_purchase action is not saving data.

so for example on the purchase action  i choose a product from the dropdown menu that I’ve already created in settings and hit save, when i leave the object with the purchase action on or hit play it reverts back to the first item in the dropdown menu.

any ideas why this is happening and how to fix?

many thanks

Send fix to: paulhannah7@me.com

**Comment by DonaldQuack** [comment]
Fixed
