### ISSUE TITLE
Social GIF html 5 example

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#19]

**Comment by frosting17** [comment]
https://dl.dropboxusercontent.com/u/83133800/StansAssets/SocialGif_HTML5/index.html

**Comment by lacosto** [comment]
Не работает, так и не смог сохранить гифку.
<img width="1092" alt="unity_webgl_player___socialgifproject" src="https://cloud.githubusercontent.com/assets/12031497/22863915/f5cf6d66-f150-11e6-8da8-0135ea8fd425.png">

Как только все будет рабоать, перекинь эту таску на меня пожайлуста.

**Comment by frosting17** [comment]
Ошибку исправил. Плагин не работает на WebGL. То бишь сохранение ты не найдешь.

**Comment by frosting17** [comment]
https://dl.dropboxusercontent.com/u/83133800/StansAssets/SocialGif_HTML5/index.html 
Перезалил.
