### ISSUE TITLE
Rewrite Ultimate Mobile documentation

### ISSUE THREAD

**Issue by AlexYaremenko** [StansAssets/Development#20]
Rewrite Ultimate Mobile setup [documentation](https://unionassets.com/ultimate-mobile/setup-and-update-219#settings-file-location)

Comment from Unity Ultimate Mobile forum thread

> This page says they're under Assets/Extensions/StansAssetsConfig/Resources, but that folder doesn't exist for me.

**Comment by lacosto** [comment]
done
