### ISSUE TITLE
AdMob Native Ads (Android & iOS)

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#202]
Android - https://developers.google.com/admob/android/native
iOS - https://developers.google.com/admob/ios/native

**Comment by AlexYaremenko** [comment]
Google AdMob Native Ads Express will be implemented.
Have no plans to integrate Native Ads Advanced for this time.
Approved by Stan.

**Comment by AlexYaremenko** [comment]
Sorry, Native Ads Express was deprecated 👎
