### ISSUE TITLE
Twitter cards (AN, iSN, MSP)

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#211]
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by AlexYaremenko** [comment]
Для того, чтобы постить Twitter Cards со стороны плагина ничего дополнительно имплементировать не нужно. И это происходит как ширанг обычной ссылки.
Рассмотрим пример шаринга ссылки на сайт. Чтобы ссылка на сайт отображалась в виде Twitter Card, нужно чтобы на сайте (прям добавить в html код) были добавлены необходимые [данные](https://twittercommunity.com/t/required-meta-tag-missing-twitter-text-description/80564).
