### ISSUE TITLE
Launch Application by clicking on notification doesn't work

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#221]

**Comment by lacosto** [comment]
Работает, на самом деле оно не может не запускать приложение.
Может только крашить при запуске приложение. А этому уже может быть связано с кодомо который написал пользователь для обработки сообщения.

Но пока проверял доабвил евент которого явно не доставало

using SA.IOSNative.UserNotifications;
NotificationCenter.OnWillPresentNotification += (NotificationRequest obj) => {
        Debug.Log("OnWillPresentNotification: " + obj.Content);
};
