### ISSUE TITLE
Create additional methods for saving data in iCloud

### ISSUE THREAD

**Issue by DonaldQuack** [StansAssets/Development#222]
https://developer.apple.com/documentation/foundation/nsubiquitouskeyvaluestore?language=objc

Part of the API already done in previous versions of the iOS Native.

1. SetData - done
2. SetDouble - done
3. SetString - done

Have to add:
SetArray
SetBool
SetDictionary
SetLongLong
SetObject

**Comment by lacosto** [comment]
Done + guide updated:
https://unionassets.com/iosnative/coding-guidelines-26
