### ISSUE TITLE
Vungle api

### ISSUE THREAD

**Issue by Cfyzik** [StansAssets/Development#225]
Необходимо обновить апи
VunglePlugin-3.1.35

http://prntscr.com/hav6f1
http://prntscr.com/hav6wd

**Comment by DonaldQuack** [comment]
Ошибки на скриншотах связаны с тем, что плагин не был обновлен до последней версии с репозитория.
Саша, ты качал не тот package.
3.1.5 released this on Jan 27, 2016 - https://github.com/Vungle/Unity-Plugin/releases

Корректная ссылка на ресурс открывается через настройки плагина:
https://dashboard.vungle.com/sdk. 
Соответственно версия Vungle 5.3.0.
Но! Действительно есть ошибка при билде под Андроид платформу. 
Для решения проблемы скидывай пацыкам линк - https://unionassets.com/ultimate-ads/i-am-getting-build-error-597.
Ошибка не на нашей стороне так как UltimateAds не содержит манифестов.
