### ISSUE TITLE
GameCircle errors

### ISSUE THREAD

**Issue by Cfyzik** [StansAssets/Development#237]
Assets/Plugins/AmazonGameCirclePlugin/Source/UnitySocialAPI/GameCircleSocial.cs(20,14): error CS0535: `GameCircleSocial' does not implement interface member `UnityEngine.SocialPlatforms.ISocialPlatform.Authenticate(UnityEngine.SocialPlatforms.ILocalUser, System.Action<bool,string>)'

Assets/Plugins/AmazonGameCirclePlugin/Source/UnitySocialAPI/AGSSocialLocalUser.cs(19,14): error CS0535: `AGSSocialLocalUser' does not implement interface member `UnityEngine.SocialPlatforms.ILocalUser.Authenticate(System.Action<bool,string>)'

**Comment by Cfyzik** [comment]
link to fix 
https://forums.developer.amazon.com/questions/52922/gamecircle-plugin-does-not-compile-under-unity-55.html

**Comment by DonaldQuack** [comment]
Баг не на нашей стороне. Описание проблемы ниже:
https://mail.google.com/mail/u/0/#search/GameCircleSocial'+does+not+implement+interface/159f4de223f1bb14
