### ISSUE TITLE
AmazonProductTemplate.cs

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#25]
Price is set incorrectly. Amazon return localized price with currency symbol string and not the actual price float value. This is different from Android. You should parse the string to extra float price from it:

https://www.evernote.com/l/APVUqRbLNH1By5qlYokvXA25Tty6T1gRjTw

**Comment by frosting17** [comment]
ожидаю ревью от Amazon.
Не могу затестить код Атул Госейна, потому что инфа об InApps приходит только после релиза приложения.

**Comment by frosting17** [comment]
фикс закомичен
