### ISSUE TITLE
Example Apps graphics for IOS and Android plugins

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#29]

**Comment by lacosto** [comment]
@frosting17  assign back to me when ready

**Comment by frosting17** [comment]
Отослал дизу примеры для будущей графы. Жду результатов

**Comment by lacosto** [comment]
как там наши успехи?

**Comment by frosting17** [comment]
Дизайн Лена вернула. Алексей делает для Android Native. 
Я буду для IOS Native.
