### ISSUE TITLE
Improve Native popups plugin API

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#30]
Желательно подумать над его АПИ. То что есть мягко говоря не очень хорошо написано.
И я думаю стоить дополнииельно сделать возможность тестить попапы прямо в редакторе.

**Comment by AlexYaremenko** [comment]
SA.Common dependencies removed

**Comment by AlexYaremenko** [comment]
Android READY
Editor Testing READY

**Comment by frosting17** [comment]
iOS READY!
