### ISSUE TITLE
Иконка для Ultimate Mobile

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#36]
Пытался подобрать иконку для этой статьи
https://unionassets.com/ultimate-mobile/overview-218

но она так и не вписалсь по стилю, должны быть более жирные контуры как и у других иконок, попроси плз дизайнера сделать иконку которая будет ассоцоироваться с кросплатформенностью и чтобы писалась со стилем других иконок, как сделает перебрось этот таск на меня, ну или сам замени обложку статьи.
Спасибо!

**Comment by frosting17** [comment]
Отдал Лене, жду иконки.
