### ISSUE TITLE
Общение с пользователями на Assetstore

### ISSUE THREAD

**Issue by frosting17** [StansAssets/Development#38]
Отвечай на хорошие ревью тоже.  Благодари за комменты, люди видят живое общение, и понимают, что за плагинами следят и поддержка постоянная.

**Comment by lacosto** [comment]
Хорошее замечание @frosting17  =) пол часа писал ответы к осноным плагинам. Ну и кстати писать ответы на хорошие отзывы - поприятнее чем на плохие =)
