### ISSUE TITLE
Request camera permission

### ISSUE THREAD

**Issue by frosting17** [StansAssets/Development#39]
Imagepicker automatically asks for permission, but If I could just call permission without launching Camera/Image Picker that would be highly helpful in my case.

**Comment by lacosto** [comment]
Добавь в локументацию плз чтобы больше не спрашивали.

1) Permission will be asked automatically when your app will start camera interaction for the first time. If a user will approve permission, permission dialog will not appear with future camera usage. If a user will deny permission, camera access for your application will be blocked, and you will not able to present permissions dialog again.
