### ISSUE TITLE
OneSignal 

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#42]
[[SKPaymentQueue defaultQueue] addPayment:payment]; - gives crush, looks like this is the oncesignal issues. 
lets let them know about it.

Вот этого чувака желательно поставить в копию
c3p1creations@gmail.com

**Comment by frosting17** [comment]
Ждем ответа от c3p1creations@gmail.com, даст ли он добро на отправку его проекта в onesignal support.

**Comment by frosting17** [comment]
Письмо отослано. Ждем ответа от OneSignal.

**Comment by frosting17** [comment]
Nailed it =)
