### ISSUE TITLE
iOS Social Sharing callback issue

### ISSUE THREAD

**Issue by AlexYaremenko** [StansAssets/Development#52]
Hello,

we're facing problem with sharing via UM_ShareUtility.InstagramShare(text, texture); on iPhone (tested on multiple devices with iOS 10.2), build with Unity 5.5.0p4 and Ultimate Mobile 9.3.

Social Sharing checkbox is ticked in iOS settings, and all other methods: Facebook, Twitter, Whatsapp and Default Share Dialog are working as expected. On Android everything works.

Sharing to Instagram finishes immediately with Error.Message "Posting Failed".

All devices have Instagram installed on them.

Does anyone have issues with Ig like we do?

**Comment by frosting17** [comment]
Протестил на всех iOS девайсах. Баг не воспроизводится.

**Comment by AlexYaremenko** [comment]
Отписал чуваку на форуме, что у нас не репродьюсится. Этот тип должен написать на почту.
Если что, потом этот кейс откроем обратно. На данный момент закрываю
