### ISSUE TITLE
Plugin's Resources are included in build by default

### ISSUE THREAD

**Issue by AlexYaremenko** [StansAssets/Development#56]
```
jbayonaberiso@gmail.com

Hello my name is Juan and I am one of your Ultimate mobile users.

Everytime I include your plugin there are a lot of icons that get included into the builds because you have this images in Editor/Resources folder, although it is correct that Editor foldes isn't included in builds, the inner Resources folder does and as a result all of my builds contain all of your icons in the final executable (apk or ipa).

To avoid this please move your icons to the folder Assets/Editor Default Resources and instead of using Resources.Load use EditorGUIUtility.Load (careful you must include the extension .png).

Thank you.
```

Ситуация следующая. Имеются ресурсы (текстуры, спрайты и т.д.), которые находятся в папке Resources. Нужно пройтись по всем плагинам, которые входят в Ultimate Mobile и переименовать эту папку, например в Art/Textures/Sprites, чтобы избежать упаковку этих ресурсов в финальный билд.

**Comment by KrasovskyVictor** [comment]
Переименовал папки Resources в плагинах iOS Native, Android Native. Не переименовал папки, вложенные в папку Editor (т.к. они не попадают в билд и используются для отрисовки в эдиторе).
