### ISSUE TITLE
Ultimate Ads Social Media Images

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#64]
Facebook:
(1200 x 630)
(Max. 8 MB)

+ Images for Union Assets

**Comment by frosting17** [comment]
Так есть же все.
![ultimate ads 1200 630](https://cloud.githubusercontent.com/assets/11818381/22853659/358efeae-f065-11e6-9b80-bce6bbe0334f.jpg)

**Comment by lacosto** [comment]
Леша мне не скинул просто.
А для Union Assets есть размеры?

**Comment by frosting17** [comment]
Жду от Лены.

**Comment by frosting17** [comment]
[UltimateAds Cover.zip](https://github.com/StansAssets/Development/files/799793/UltimateAds.Cover.zip)

**Comment by frosting17** [comment]
Александр занят тасками. asap.
