### ISSUE TITLE
Logger cover

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#65]

**Comment by frosting17** [comment]
14 февраля brainstorm на тему обложки.

**Comment by frosting17** [comment]
Отдал Лене описание с примерами, что должно быть на обложке.

**Comment by frosting17** [comment]
Архив с обложками.
[Logger Cover.zip](https://github.com/StansAssets/Development/files/789638/Logger.Cover.zip)

**Comment by lacosto** [comment]
done
