### ISSUE TITLE
iOS Native  -  native issues.

### ISSUE THREAD

**Issue by frosting17** [StansAssets/Development#74]
1 import plugin.
I’m using Unity4.7.2f1 pro with  plugin version 9.4/17.

2 build    
*build and run fails on my machine
with ios build settings.
scripting background to IL2CPP 
Architecture to Universal 

3 open the project in Xcode 8.2.1.
*In this step, I need to add frameworks manually.It seems post process not woking correctly.
 
4 build 
deployment target 8.0

The attached is the screenshot of that error.
![1](https://cloud.githubusercontent.com/assets/11818381/23305907/a0684728-faa9-11e6-8aad-a196818a139e.png)

**Comment by lacosto** [comment]
fixed
