### ISSUE TITLE
Add projects to documentation

### ISSUE THREAD

**Issue by lacosto** [StansAssets/Development#87]
Hi Stan! We just wanted to again thank you and your team for the great help in getting our app working properly. We launched it yesterday and just wanted to let you know. If you'd like to take a look, it's here on iOS and Android:

https://itunes.apple.com/app/id1138078098

https://play.google.com/store/apps/details?id=com.c3p1creations.supermadcow

If you'd like to use Super Mad Cow in promoting your plugins, please feel free to do so. We used both iOS Native and Android Native plugins, with no regrets. Great plugins!

**Comment by frosting17** [comment]
Done
